[System]
Name: Mock Model

[Parameter]
-- All parameters declared using integers so that our plugins can handle floating point
-- partitioning.

betavis (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
za_lake (int) : 0, 1, 2, 3, 4, 5
n2min (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
pudz (int): 0, 1
mixfact (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
depthcrit (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

