[System]
Name: Lake Temperature SPEL Unit Test

[Parameter]
-- All parameters declared using integers so that our plugins can handle floating point
-- partitioning.
-- Each float given 10 values, boolean given 2, and int given 10 except for nlevsno.

-- Fraction of VIS treated as NIR
betavis (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

-- Fully explicit (0.0) - fully implicit (1.0)
cnfac (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

-- Eddy Diffusion
lake_no_ed (int) : 0, 1

-- Lake Puddling
lakepuddling (int) : 0, 1

-- Methane coupling
use_lch4 (int) : 0, 1

-- Vertical Resolution
nlevlak (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
nlevgrnd (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
nlevsno (int) : 0, 1, 2, 3, 4, 5
nlevsoi (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

-- Time step
dtime_mod (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

-- Physical Constants
cpliq (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
denh2o (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
tkwat (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
thk_bedrock (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
vkc (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
grav (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
hfus (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

-- Constants that have an affect on checks but not model output
denice (int) : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
