binary_path: elmtest/elmtest.exe
range_path: elmtest/FUT_lake_range.txt
params_path: elmtest/lakeparams.txt
defaults_path: elmtest/lakeparams_defaults.txt
ref_output: elmtest/cpu_LakeTemperatureRef.txt
test_output: elmtest/cpu_LakeTemperatureTest.txt
order_directory: mapping_orders
binary_args: 1
