binary_path: fake_binary/fake_binary.exe
range_path: fake_binary/FUT_lake_range.txt
params_path: fake_binary/lakeparams.txt
defaults_path: fake_binary/lakeparams_defaults.txt
ref_output: fake_binary/fake_LakeTemperatureRef.txt
test_output: fake_binary/fake_LakeTemperatureTest.txt
order_directory: mapping_orders
output_directory: mapping_output
binary_args: 
