[System]
Name: Lake Temperature SPEL Unit Test

[Parameter]
-- All parameters declared using integers so that our plugins can handle floating point partitioning.
-- Each float given 11 values and boolean given 2.

tkwat (int) : 0,1,2,3,4,5,6,7,8,9,10
cpice (int) : 0,1,2,3,4,5,6,7,8,9,10
cnfac (int) : 0,1,2,3,4,5,6,7,8,9,10
pudz (int) : 0,1,2,3,4,5,6,7,8,9,10
vkc (int) : 0,1,2,3,4,5,6,7,8,9,10
mixfact (int) : 0,1,2,3,4,5,6,7,8,9,10
cpliq (int) : 0,1,2,3,4,5,6,7,8,9,10
depthcrit (int) : 0,1,2,3,4,5,6,7,8,9,10
tkice (int) : 0,1,2,3,4,5,6,7,8,9,10
betavis (int) : 0,1,2,3,4,5,6,7,8,9,10
denice (int) : 0,1,2,3,4,5,6,7,8,9,10
dtime_mod (int) : 0,1,2,3,4,5,6,7,8,9,10
hfus (int) : 0,1,2,3,4,5,6,7,8,9,10
grav (int) : 0,1,2,3,4,5,6,7,8,9,10
lakepuddling (int) : 0,1
denh2o (int) : 0,1,2,3,4,5,6,7,8,9,10
lake_no_ed (int) : 0,1
use_lch4 (int) : 0,1
tkair (int) : 0,1,2,3,4,5,6,7,8,9,10
thk_bedrock (int) : 0,1,2,3,4,5,6,7,8,9,10

[Constraint]
lakepuddling = 0 => pudz = 0
